- icon: 'icon ion-coffee'
  title: 'Branding'
  content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae asperiores pariatur quod fuga magni.'

- icon: 'ion-compass'
  title: 'Web Design'
  content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae asperiores pariatur quod fuga magni.'

- icon: 'ion-image'
  title: 'App Design'
  content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
    eiusmod tempor incididunt ut'

- icon: 'ion-bug'
  title: 'Start Up'
  content: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur animi soluta obcaecati nemo commodi.'

- icon: 'ion-headphone'
  title: 'Logo Design'
  content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae asperiores pariatur quod fuga magni.'

- icon: 'ion-leaf'
  title: 'Development'
  content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
    eiusmod tempor incididunt ut'

- icon: 'ion-planet'
  title: 'Brand Identity'
  content: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur animi soluta obcaecati nemo commodi.'

- icon: 'ion-earth'
  title: 'Brand Identity'
  content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
    eiusmod tempor incididunt ut'
